<a href="https://colab.research.google.com/github/Bhawanand394/Basics-of-Machine-learning/blob/main/Bhawanand_Jha_2401020456_Experiment_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as r

In [2]:
import matplotlib.pyplot as gr

In [3]:
from sklearn.datasets import load_iris

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
def fibonacii(term):
  if (term<=1):
    return term
  else:
    return (fibonacii(term-1)+fibonacii(term-2))

In [7]:
term=int(input("Enter the number:-"))
for i in range(1, term+1):
  print(fibonacii(i))

Enter the number:-20
1
1
2
3
5
8
13
21
34
55
89
144
233
377
610
987
1597
2584
4181
6765


In [8]:
irisdata = load_iris()

In [9]:
x = irisdata.data

In [10]:
y = irisdata.target

In [11]:
print(x)
print(y)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [13]:
print(x.shape)

(150, 4)


In [14]:
print(y.shape)

(150,)


In [28]:
count = (y ==1).sum()
print(count)

50


In [76]:
def evaluating_testing(test_size):
    x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42,stratify=y)
    return x_train, x_test, y_train, y_test

In [77]:
from sklearn.naive_bayes import GaussianNB

In [78]:
x_train, x_test, y_train, y_test = evaluating_testing(0.2)

In [79]:
model = GaussianNB()

In [80]:
model.fit(x_train, y_train)

AttributeError: 'numpy.ndarray' object has no attribute '_validate_params'